apiVersion: v1
kind: PersistentVolume
metadata:
  name: brain-tumor-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /home/ubuntu/projects/brain-tumor-detection/media
